-- 5A
SELECT

    S.FNAME || ' ' || S.LNAME AS "STUDENT NAME",
    S.SID AS "GRADE 12 NUMBER",
    CASE
        WHEN B.RES_ID IS NOT NULL THEN RH.NAME
        ELSE 'Student Flat'
    END AS BUILDING,
    R.ROOM,
    L.YEAR,
    SEM.NAME AS "SEMESTER",
    L.DURATION,
    L.ENTER AS"ENTER DATE",
    L.EXIT AS "EXIT DATE"

FROM STUDENT S
JOIN LEASE L ON S.SID = L.STUDENT_ID
JOIN SEMESTER SEM ON L.SEMESTER_ID = SEM.MID
JOIN ROOM R ON L.ROOM_ID = R.PID
JOIN BUILDING B ON R.BID = B.BID
LEFT JOIN STUDENTFLAT SF ON B.FLAT_ID = SF.FID
LEFT JOIN RESIDENCEHALL RH ON B.RES_ID = RH.RID;

-- 5B
SELECT

    S.FNAME || ' ' || S.LNAME AS "STUDENT NAME",
    S.SID AS "GRADE 12 NUMBER",
    '$' || SUM(I.PAYDUE) AS "TOTAL RENT PAID TO DATE"
    
FROM STUDENT S
JOIN LEASE L ON S.SID = L.STUDENT_ID
JOIN INVOICE I ON L.LID = I.LEASE_ID
WHERE I.PAID_DATE IS NOT NULL
GROUP BY S.FNAME || ' ' || S.LNAME, S.SID;

-- 5C
SELECT

    S.FNAME || ' ' || S.LNAME AS "STUDENT NAME",
    S.SID AS "GRADE 12 NUMBER",
    '$' || I.PAYDUE AS "AMOUNT OWED",
    CASE SEM.NAME
        WHEN 'Fall' THEN L.YEAR || '/09/01'
        WHEN 'WINTER' THEN (L.YEAR + 1) || '/01/01' 
        ELSE (L.YEAR + 1) || '/01/05'
    END AS "DUE DATE"
    
FROM STUDENT S
JOIN LEASE L ON S.SID = L.STUDENT_ID
JOIN INVOICE I ON L.LID = I.LEASE_ID
JOIN SEMESTER SEM ON I.SEMESTER_ID = SEM.MID
WHERE I.PAID_DATE IS NULL
  AND SYSDATE > CASE SEM.NAME
                    WHEN 'Fall' THEN L.YEAR || '/09/01'
                    WHEN 'WINTER' THEN (L.YEAR + 1) || '/01/01' 
                    ELSE (L.YEAR + 1) || '/01/05'
                END;

-- 5D
SELECT

    FI.FID AS "FLAT ID",
    B.ADDRESS,
    FI.I_DATE AS "INSPECTION DATE",
    FI.INSPECTOR_ID AS "INSPECTOR ID",
    S.FNAME || ' ' || S.LNAME AS "INSPECTOR NAME",
    FI.SATISFACTORY,
    FI.AD_COMMENT AS "COMMENTS"

FROM FLATINSPECTION FI
JOIN BUILDING B ON FI.FID = B.FLAT_ID
JOIN STAFF S ON FI.INSPECTOR_ID = S.HID
WHERE SATISFACTORY = 'N';

-- 5E
SELECT

    S.FNAME || S.LNAME AS "STUDENT NAME",
    S.SID AS "GRADE 12 NUMBER",
    RH.NAME AS "RESIDENCE HALL",
    R.PID AS "PLACE NUMBER",
    R.ROOM AS "ROOM NUMBER"
    
FROM STUDENT S
JOIN LEASE L ON S.SID = L.STUDENT_ID
JOIN ROOM R ON L.ROOM_ID = R.PID
JOIN BUILDING B ON R.BID = B.BID
JOIN RESIDENCEHALL RH ON B.RES_ID = RH.RID
WHERE RH.RID = 1;

-- 5F
SELECT

    S.FNAME || ' ' || S.LNAME AS "STUDENT NAME",
    S.SID AS "GRADE 12 NUMBER",
    STF.FNAME || ' ' || STF.LNAME AS "ADVISOR NAME",
    S.ADVISOR_ID AS "STAFF ID",
    S.ADDRESS AS "HOME ADDRESS",
    S.BIRTHDAY,
    C.NAME AS "CATEGORY",
    G.NAME AS "GENDER",
    N.NAME AS "NATIONALITY",
    D.NAME AS "DEGREE",
    S.NEEDS,
    S.AD_COMMENT AS "COMMENTS"

FROM STUDENT S
JOIN ADVISOR A ON S.ADVISOR_ID = A.AID
JOIN STAFF STF ON A.AID = STF.HID
JOIN CATEGORY C ON S.CATEGORY_ID = C.CID
JOIN GENDER G ON S.GENDER_ID = G.GID
JOIN NATIONALITY N ON S.NATIONALITY_ID = N.NID
JOIN DEGREE D ON S.DEGREE_ID = D.DID
WHERE STATUS = 'W';

-- 5G
SELECT

    C.NAME AS "CATEGORY",
    COUNT(C.NAME) AS "NUMBER OF STUDENTS"

FROM STUDENT S
JOIN CATEGORY C ON S.CATEGORY_ID = C.CID
GROUP BY C.NAME
ORDER BY 2 DESC;

-- 5H
SELECT

    S.FNAME || ' ' || S.LNAME AS "STUDENT NAME",
    S.SID AS "GRADE 12 NUMBER",
    STF.FNAME || ' ' || STF.LNAME AS "ADVISOR NAME",
    S.ADVISOR_ID AS "STAFF ID",
    A.DEPARTMENT,
    A.TELENUM AS "INTERNAL #"

FROM STUDENT S
JOIN ADVISOR A ON S.ADVISOR_ID = A.AID
JOIN STAFF STF ON A.AID = STF.HID
WHERE S.SID = 101020304;

-- 5I
SELECT

    RH.NAME,
    '$' || MIN(R.RENT) "MIN RENT",
    '$' || MAX(R.RENT) "MAX RENT",
    '$' || AVG(R.RENT) "AVG RENT"
    
FROM RESIDENCEHALL RH
JOIN BUILDING B ON RH.RID = B.RES_ID
JOIN ROOM R ON B.BID = R.BID
GROUP BY RH.NAME;

-- 5J
SELECT

    S.HID AS "STAFF ID",
    S.FNAME || ' ' || S.LNAME AS "STAFF NAME",
    ROUND((SYSDATE - S.BIRTHDAY)/365, 0) AS "AGE (YEARS)",
    S.LOCATION

FROM STAFF S
JOIN GENDER G ON S.GENDER_ID = G.GID
WHERE ROUND((SYSDATE - S.BIRTHDAY)/365, 0) >= 40;