
set transaction name 'create_database';

create table gender (
    gid     smallint generated by default on null as identity primary key, /* Generic Gender ID */
    name    varchar2(32) not null unique
);

create table semester (
    mid     smallint generated by default on null as identity primary key, /* Generic Semester ID */
    name    varchar2(64) not null unique
);

create table category (
    cid     smallint generated by default on null as identity primary key, /* Generic Category ID */
    name    varchar2(64) not null unique
);

create table nationality (
    nid     smallint generated by default on null as identity primary key, /* Generic Nationality ID */
    name    varchar2(64) not null unique
);

create table degree (
    did     smallint generated by default on null as identity primary key, /* Generic Degree ID */
    name    varchar2(64) not null unique
);

create table paytype (
    tid     smallint generated by default on null as identity primary key, /* Generic PayType ID */
    name    varchar2(64) not null unique
);

create table staff (
    hid         smallint generated by default on null as identity primary key, /* Staff number */
    fname       varchar2(24) not null,
    lname       varchar2(32) not null,
    address     varchar2(100) not null,
    birthday    date not null,
    position    varchar2(24) not null,
    location    varchar2(24) not null,
    gender_id   smallint,
    foreign key (gender_id) references gender (gid)
);

create table advisor (
    aid         smallint primary key, /* Staff number */
    department  varchar2(32) not null,
    telenum     number(15) not null,
    room        number(9) unique,
    foreign key (aid) references staff (hid)
);

create table studentflat (
    fid         smallint generated by default on null as identity primary key, /* Flat number */
    bedrooms    smallint not null,
    check (bedrooms >= 3 and bedrooms <= 5)
);

create table flatinspection (
    fid             smallint, /* Flat number */
    i_date          date,
    primary key (fid, i_date),
    inspector_id    smallint not null, /* Staff number */
    satisfactory    char(1byte) not null, /* Y = Yes, N = No */
    ad_comment      varchar2(250),
    foreign key (fid) references studentflat (fid),
    foreign key (inspector_id) references staff (hid)
);

create table residencehall (
    rid         smallint generated by default on null as identity primary key, /* Generic Residence Hall ID */
    name        varchar2(64) not null unique,
    telenum     number(15) not null,
    manager_id  smallint not null, /* Staff number */
    foreign key (manager_id) references staff (hid)
);

create table building (
    bid     smallint generated by default on null as identity primary key, /* Generic Building ID */
    address varchar2(100) not null,
    type    char (1byte) not null, /* R = Residence hall, F = Student Flat */
    res_id smallint, /* Residence Hall ID */
    flat_id smallint, /* Student Flat number */
    foreign key (res_id) references residencehall (rid),
    foreign key (flat_id) references studentflat (fid)
);

create table room (
    pid     smallint generated by default on null as identity primary key, /* Unique Place Number */
    bid     smallint not null, /* Containing Building ID */
    room    smallint not null, /* Some room number */
    rent    number(7,2) not null, /* Monthly rate */
    foreign key (bid) references building (bid)
);

create table student (
    sid         number(9) primary key, /* Student number */
    advisor_id  smallint not null, /* Staff number */
    fname       varchar2(24) not null, /* First name */
    lname       varchar2(32) not null, /* Last name */
    address     varchar2(100) not null,
    birthday    date not null,
    category_id smallint not null,  /* Postgrad, first year undergrad, etc. */
    status      char,           /* 'W' = Wating, 'P' = Placed */
    gender_id   smallint,
    nationality_id smallint,
    degree_id   smallint,
    needs       varchar2(250),
    ad_comment  varchar2(250),
    foreign key (advisor_id) references advisor (aid),
    foreign key (category_id) references category (cid),
    foreign key (gender_id) references gender (gid),
    foreign key (nationality_id) references nationality (nid),
    foreign key (degree_id) references degree (did)
);

create table lease (
    lid         int generated by default on null as identity primary key,
    student_id  number(9) not null,
    room_id     smallint not null,
    year        number(4) not null,
    semester_id smallint not null,
    duration    smallint not null,
    check (duration >= 1 and duration <= 3),
    enter       date,
    exit        date,
    foreign key (student_id) references student (sid),
    foreign key (room_id) references room (pid),
    foreign key (semester_id) references semester (mid)
);

create table invoice (
    iid         int generated by default on null as identity primary key,
    lease_id    int not null,
    semester_id smallint not null,
    paydue      number(7,2) not null,
    paid_date   date, /* Null if hasn't been paid yet */
    paytype_id  smallint, /* Null if hasn't been paid yet */
    reminder1   date, /* Null if not given out yet */
    reminder2   date  /* Null if not given out yet */
);

commit;
